Traceback (most recent call last):
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\mbrown2\Anaconda3\envs\steve\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# load weather and location data, use pvlib read_psm3 function with map_variables = True

sam_file = r'example data\psm3.csv'
weather, meta = pvlib.iotools.read_psm3(sam_file, map_variables = True)
#weather, meta = pvlib.iotools.read_psm3(sam_file)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[2], line 4[0m
[0;32m      1[0m [38;5;66;03m# load weather and location data, use pvlib read_psm3 function with map_variables = True[39;00m
[0;32m      3[0m sam_file [38;5;241m=[39m [38;5;124mr[39m[38;5;124m'[39m[38;5;124mexample data[39m[38;5;124m\[39m[38;5;124mpsm3.csv[39m[38;5;124m'[39m
[1;32m----> 4[0m weather, meta [38;5;241m=[39m [43mpvlib[49m[38;5;241;43m.[39;49m[43miotools[49m[38;5;241;43m.[39;49m[43mread_psm3[49m[43m([49m[43msam_file[49m[43m,[49m[43m [49m[43mmap_variables[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[0;32m      5[0m [38;5;66;03m#weather, meta = pvlib.iotools.read_psm3(sam_file)[39;00m

File [1;32m~\Documents\GitHub\pvlib\pvlib\iotools\psm3.py:412[0m, in [0;36mread_psm3[1;34m(filename, map_variables)[0m
[0;32m    375[0m [38;5;28;01mdef[39;00m [38;5;21mread_psm3[39m(filename, map_variables[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m    376[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m    377[0m [38;5;124;03m    Read an NSRDB PSM3 weather file (formatted as SAM CSV). The NSRDB[39;00m
[0;32m    378[0m [38;5;124;03m    is described in [1]_ and the SAM CSV format is described in [2]_.[39;00m
[1;32m   (...)[0m
[0;32m    410[0m [38;5;124;03m       <https://web.archive.org/web/20170207203107/https://sam.nrel.gov/sites/default/files/content/documents/pdf/wfcsv.pdf>`_[39;00m
[0;32m    411[0m [38;5;124;03m    """[39;00m
[1;32m--> 412[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[38;5;28;43mstr[39;49m[43m([49m[43mfilename[49m[43m)[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m fbuf:
[0;32m    413[0m         content [38;5;241m=[39m parse_psm3(fbuf, map_variables)
[0;32m    414[0m     [38;5;28;01mreturn[39;00m content

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'example data\\psm3.csv'

